### PR TITLE
fix(parser): Resolve `autodocs` tag issue and extracting `rawCode`

### LINKED ISSUE #199: [Bug]: `autodocs` using `svelte-csf` `v5` does not render individual story within docs
### Describe the bug

I have been using this addon on a toy project. Its been observed that when `autodocs` is used, docs page does not render individual stories.

### Steps to reproduce the behavior

Here's the [reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-bxesk4) of the issue.

For some unknown reason, stackblitz does not save `.storybook` folder. Hence, `storybook init` will have to be run to render storybook

### Expected behavior

`docs` page for `stories/Button` component that uses this addon should render individual stories such as `Primary`, `Secondary` etc.

### Screenshots and/or logs

image

### Environment

 - OS: OSX
 - Node.js version: 22.3
 - NPM version: pnpm

### PR DESCRIPTION
**Pull request by xeho91**
Resolves #199

Updated reproduction for manual testing in development mode: https://stackblitz.com/edit/sveltejs-kit-template-default-132muy

## Fixed:

1. Analyzing `Attribute` AST node value when it can be a single `ExpressionTag`
2. Walking on compiled Stories component function to extract `Story` definitions

<details>
  <summary>📦 Published PR as canary version: <code>4.2.0--canary.201.928fe20.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/addon-svelte-csf@4.2.0--canary.201.928fe20.0
  # or 
  yarn add @storybook/addon-svelte-csf@4.2.0--canary.201.928fe20.0
  ```
</details>

### CODE REVIEW

**Comment by xeho91** [comment]
@JReinhold 

Workflow `Check / Test` _(with `svelte-check`)_ failure is expected. Is related to https://github.com/sveltejs/svelte/issues/12292

**Comment by xeho91** [comment]
Converting back to draft, need further inspection. I was checking only on Chromatic for now.

But then, I checked in development mode on my device, and the issue still persists.

File: src/utils/error.ts [hunk 1]
```diff
@@ -111,23 +111,35 @@ export abstract class StorybookSvelteCSFError extends Error {
   // WARN: I had to duplicate logic. We already have functions for it.
   // But we can't import it, because it would create a cyclic-dependency.
   protected get storyNameFromAttribute() {
-    if (this.component) {
-      for (const attribute of this.component?.attributes) {
+    const { component } = this;
+    const { attributes } = component;
+    if (component) {
```
Comment (JReinhold) [inline src/utils/error.ts:116]: 1. wouldn't line 115 throw if `component` was `undefined`? or otherwise, if `component` can't be `undefined`, then is the condition on 116 needed?
2. If the condition on `component` is actually needed, I think it should be reversed to be an early return instead.

Personally I'd go with:

```
if (!this.component) {
  return ...;
}
for (const attribute of this.component?.attributes) {
  ...
}
```

File: src/utils/error.ts [hunk 2]
```diff
@@ -111,23 +111,35 @@ export abstract class StorybookSvelteCSFError extends Error {
...
-            typeof attribute.value[0].expression.value === 'string'
+            value[0].type === 'ExpressionTag' &&
+            value[0].expression.type === 'Literal' &&
+            typeof value[0].expression.value === 'string'
           ) {
-            return attribute.value[0].expression.value;
+            return value[0].expression.value;
           }
         }
       }
```
Comment (JReinhold) [inline src/utils/error.ts:145]: (I can't comment on the correct line 148), but wouldn't it be more correct to be `return '<UnnamedComponent>';` instead?

File: src/utils/error/parser/analyse/story.ts [hunk 3]
```diff
@@ -55,10 +55,17 @@ export class AttributeNotArrayError extends StorybookSvelteCSFError {
   }
 
   get valueType() {
-    const { value } = this.attribute;
+    const { attribute } = this;
+    const { value } = attribute;
```
Comment (JReinhold) [inline src/utils/error/parser/analyse/story.ts:59]: nit: I actually think the old logic reads better, but it's not a strong oppinion.

**Review by JReinhold — APPROVED** [review]
a tiny question about safety, otherwise it looks good!

File: src/utils/error.ts (hunk 1 above)
Comment (xeho91) [reply src/utils/error.ts:116]: Good catch!

File: src/utils/error.ts (hunk 2 above)
Comment (xeho91) [reply src/utils/error.ts:141]: Done

File: src/parser/analyse/story/attributes.test.ts [hunk 4]
```diff
@@ -37,9 +37,9 @@ describe(getStringValueFromAttribute.name, () => {
       .toThrowErrorMatchingInlineSnapshot(`
         [SB_SVELTE_CSF_PARSER_ANALYSE_STORY_0001 (AttributeNotStringError): In the stories file: <path not specified>
 
-        A '<Story name="<unspecified Story name>" />' has a prop 'name' whose value must be a static literal string.
+        A '<Story name="undefined" />' has a prop 'name' whose value must be a static literal string.
```
[the remark this answers is not in the document]
Comment (JReinhold) [reply src/parser/analyse/story/attributes.test.ts:40]: I'm actually also similarly confused about it. We'll see what happens. 🚀

**Comment by shilman** [comment]
:rocket: PR was released in [`v5.0.0-next.2`](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v5.0.0-next.2) :rocket:

File: src/parser/analyse/story/attributes.test.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (JReinhold) [reply src/parser/analyse/story/attributes.test.ts:40]: Phew https://github.com/storybookjs/addon-svelte-csf/releases/tag/v5.0.0-next.2 😅

I guess it's just the canary versioning that's a little broken with `auto`.
